#####--------传统视觉调参--------#####
threshold: 150
max_angle_error: 45 
min_lightbar_ratio: 1.0
max_lightbar_ratio: 20
min_lightbar_length: 8
min_armor_ratio: 1
max_armor_ratio: 5
max_side_ratio: 1.5
max_rectangular_error: 20
min_confidence: 0.8

#####--------串口--------#####
serial_port: "/dev/ttyCH341USB0"
baudrate: 152000

#####--------分类器参数--------#####
classify_model: "/home/c/rm_xz_vision26/assets/tiny_resnet.onnx"

#####--------相机曝光--------#####
camera_name: "hikrobot"
exposure_ms: 2
gain: 16
vid_pid: "2bdf:0001"